countryCodes: [
    { value: '+1', label: '+1 (United States, Canada, Mexico, etc.)' },
    { value: '+44', label: '+44 (United Kingdom)' },
    { value: '+91', label: '+91 (India)' },
    { value: '+61', label: '+61 (Australia)' },
    { value: '+81', label: '+81 (Japan)' },
    { value: '+33', label: '+33 (France)' },
    { value: '+49', label: '+49 (Germany)' },
    { value: '+34', label: '+34 (Spain)' },
    { value: '+39', label: '+39 (Italy)' },
    { value: '+55', label: '+55 (Brazil)' },
    { value: '+27', label: '+27 (South Africa)' },
    { value: '+86', label: '+86 (China)' },
    { value: '+7', label: '+7 (Russia, Kazakhstan)' },
    { value: '+52', label: '+52 (Mexico)' },
    { value: '+64', label: '+64 (New Zealand)' },
    { value: '+966', label: '+966 (Saudi Arabia)' },
    { value: '+82', label: '+82 (South Korea)' },
    { value: '+20', label: '+20 (Egypt)' },
    { value: '+41', label: '+41 (Switzerland)' },
    { value: '+31', label: '+31 (Netherlands)' },
    { value: '+46', label: '+46 (Sweden)' },
    { value: '+48', label: '+48 (Poland)' },
    { value: '+32', label: '+32 (Belgium)' },
    { value: '+353', label: '+353 (Ireland)' },
    { value: '+62', label: '+62 (Indonesia)' },
    { value: '+54', label: '+54 (Argentina)' },
    { value: '+56', label: '+56 (Chile)' },
    { value: '+64', label: '+64 (New Zealand)' },
    { value: '+380', label: '+380 (Ukraine)' },
    { value: '+92', label: '+92 (Pakistan)' },
    { value: '+63', label: '+63 (Philippines)' },
    { value: '+977', label: '+977 (Nepal)' },
    { value: '+98', label: '+98 (Iran)' },
    { value: '+963', label: '+963 (Syria)' },
    { value: '+254', label: '+254 (Kenya)' },
    { value: '+855', label: '+855 (Cambodia)' },
    { value: '+234', label: '+234 (Nigeria)' },
    { value: '+254', label: '+254 (Kenya)' },
    { value: '+359', label: '+359 (Bulgaria)' },
    { value: '+375', label: '+375 (Belarus)' },
    { value: '+354', label: '+354 (Iceland)' },
    { value: '+977', label: '+977 (Nepal)' },
    { value: '+995', label: '+995 (Georgia)' },
    { value: '+974', label: '+974 (Qatar)' },
    { value: '+850', label: '+850 (North Korea)' },
    { value: '+966', label: '+966 (Saudi Arabia)' },
    { value: '+1', label: '+1 (United States, Canada, Mexico, etc.)' },
    { value: '+82', label: '+82 (South Korea)' },
    { value: '+212', label: '+212 (Morocco)' },
    { value: '+971', label: '+971 (United Arab Emirates)' },
    { value: '+60', label: '+60 (Malaysia)' },
    { value: '+91', label: '+91 (India)' },
    { value: '+93', label: '+93 (Afghanistan)' },
    { value: '+973', label: '+973 (Bahrain)' },
    { value: '+1242', label: '+1242 (Bahamas)' },
    { value: '+267', label: '+267 (Botswana)' },
    { value: '+855', label: '+855 (Cambodia)' },
    { value: '+226', label: '+226 (Burkina Faso)' },
    { value: '+228', label: '+228 (Togo)' },
    { value: '+234', label: '+234 (Nigeria)' },
    { value: '+261', label: '+261 (Madagascar)' },
    { value: '+685', label: '+685 (Samoa)' },
    { value: '+255', label: '+255 (Tanzania)' },
    { value: '+678', label: '+678 (Vanuatu)' },
    { value: '+1849', label: '+1849 (Dominican Republic)' },
    { value: '+1868', label: '+1868 (Trinidad and Tobago)' },
    { value: '+1880', label: '+1880 (Barbados)' },
    { value: '+1', label: '+1 (USA, Canada, Mexico, etc.)' },
    { value: '+44', label: '+44 (United Kingdom)' },
    { value: '+971', label: '+971 (UAE)' },
    { value: '+54', label: '+54 (Argentina)' },
    { value: '+62', label: '+62 (Indonesia)' },
    { value: '+93', label: '+93 (Afghanistan)' },
    { value: '+54', label: '+54 (Argentina)' },
    { value: '+96', label: '+96 (Seychelles)' },
    { value: '+81', label: '+81 (Japan)' },
    { value: '+222', label: '+222 (Mauritania)' },
    { value: '+43', label: '+43 (Austria)' },
    { value: '+501', label: '+501 (Belize)' },
    { value: '+506', label: '+506 (Costa Rica)' },
    { value: '+503', label: '+503 (El Salvador)' },
    { value: '+504', label: '+504 (Honduras)' },
    { value: '+505', label: '+505 (Nicaragua)' },
    { value: '+507', label: '+507 (Panama)' },
    { value: '+508', label: '+508 (Saint Pierre and Miquelon)' },
    { value: '+509', label: '+509 (Haiti)' },
    { value: '+591', label: '+591 (Bolivia)' },
    { value: '+593', label: '+593 (Ecuador)' },
    { value: '+594', label: '+594 (French Guiana)' },
    { value: '+595', label: '+595 (Paraguay)' },
    { value: '+596', label: '+596 (Martinique)' },
    { value: '+597', label: '+597 (Suriname)' },
    { value: '+598', label: '+598 (Uruguay)' },
    { value: '+599', label: '+599 (Curaçao)' },
    { value: '+20', label: '+20 (Egypt)' },
    { value: '+33', label: '+33 (France)' },
    { value: '+40', label: '+40 (Romania)' },
    { value: '+41', label: '+41 (Switzerland)' },
    { value: '+47', label: '+47 (Norway)' },
    { value: '+48', label: '+48 (Poland)' },
    { value: '+49', label: '+49 (Germany)' },
    { value: '+51', label: '+51 (Peru)' },
    { value: '+52', label: '+52 (Mexico)' },
    { value: '+53', label: '+53 (Cuba)' },
    { value: '+54', label: '+54 (Argentina)' },
    { value: '+55', label: '+55 (Brazil)' },
    { value: '+56', label: '+56 (Chile)' },
    { value: '+57', label: '+57 (Colombia)' },
    { value: '+58', label: '+58 (Venezuela)' },
    { value: '+59', label: '+59 (Dutch Caribbean)' },
    { value: '+60', label: '+60 (Malaysia)' },
    { value: '+61', label: '+61 (Australia)' },
    { value: '+62', label: '+62 (Indonesia)' },
    { value: '+63', label: '+63 (Philippines)' },
    { value: '+64', label: '+64 (New Zealand)' },
    { value: '+65', label: '+65 (Singapore)' },
    { value: '+66', label: '+66 (Thailand)' },
    { value: '+67', label: '+67 (Western Australia)' },
    { value: '+68', label: '+68 (Timor Leste)' },
    { value: '+69', label: '+69 (Indian Ocean Territories)' },
    { value: '+70', label: '+70 (Romania)' },
    { value: '+71', label: '+71 (Norway)' },
    { value: '+72', label: '+72 (Fiji)' },
    { value: '+73', label: '+73 (Seychelles)' },
    { value: '+74', label: '+74 (Turkmenistan)' },
    { value: '+75', label: '+75 (Uzbekistan)' },
    { value: '+678', label: '+678 (Vanuatu)' },
    { value: '+379', label: '+379 (Vatican City)'},
    { value: '+58', label: '+58 (Venezuela)'},
    { value: '+84', label: '+84 (Vietnam)'},
    { value: '+1', label: '+1 (Virgin Islands)'},
    { value: '+681', label: '+681 (Wallis and Futuna)'},
    { value: '+967', label: '+967 (Yemen)'},
    { value: '+260', label: '+260 (Zambia)'},
    { value: '+263', label: '+263 (Zimbabwe)'},
]