// nationalities.js

export const nationalities = [
    { name: 'Afghan' },
    { name: 'Albanian' },
    { name: 'Algerian' },
    { name: 'American' },
    { name: 'Andorran' },
    { name: 'Angolan' },
    { name: 'Antiguan' },
    { name: 'Argentine' },
    { name: 'Armenian' },
    { name: 'Australian' },
    { name: 'Austrian' },
    { name: 'Azerbaijani' },
    { name: 'Bahaman' },
    { name: 'Bahraini' },
    { name: 'Bangladeshi' },
    { name: 'Barbadian' },
    { name: 'Belgian' },
    { name: 'Belizean' },
    { name: 'Beninese' },
    { name: 'Bhutanese' },
    { name: 'Bolivian' },
    { name: 'Bosnian' },
    { name: 'Botswanan' },
    { name: 'Brazilian' },
    { name: 'British' },
    { name: 'Bruneian' },
    { name: 'Bulgarian' },
    { name: 'Burkinabe' },
    { name: 'Burundian' },
    { name: 'Cambodian' },
    { name: 'Cameroonian' },
    { name: 'Canadian' },
    { name: 'Cape Verdean' },
    { name: 'Central African' },
    { name: 'Chadian' },
    { name: 'Chilean' },
    { name: 'Chinese' },
    { name: 'Colombian' },
    { name: 'Comorian' },
    { name: 'Congolese' },
    { name: 'Costa Rican' },
    { name: 'Croatian' },
    { name: 'Cuban' },
    { name: 'Cypriot' },
    { name: 'Czech' },
    { name: 'Danish' },
    { name: 'Djiboutian' },
    { name: 'Dominican' },
    { name: 'Dominican Republic' },
    { name: 'Egyptian' },
    { name: 'Emirati' },
    { name: 'Equatorial Guinean' },
    { name: 'Eritrean' },
    { name: 'Estonian' },
    { name: 'Ethiopian' },
    { name: 'Fijian' },
    { name: 'Filipino' },
    { name: 'Finnish' },
    { name: 'French' },
    { name: 'Gabonese' },
    { name: 'Gambian' },
    { name: 'Georgian' },
    { name: 'German' },
    { name: 'Ghanaian' },
    { name: 'Greece' },
    { name: 'Grenadian' },
    { name: 'Guatemalan' },
    { name: 'Guinean' },
    { name: 'Guyanese' },
    { name: 'Haitian' },
    { name: 'Honduran' },
    { name: 'Hungarian' },
    { name: 'Icelander' },
    { name: 'Indian' },
    { name: 'Indonesian' },
    { name: 'Iranian' },
    { name: 'Iraqi' },
    { name: 'Irish' },
    { name: 'Israeli' },
    { name: 'Italian' },
    { name: 'Jamaican' },
    { name: 'Japanese' },
    { name: 'Jordanian' },
    { name: 'Kazakhstani' },
    { name: 'Kenyan' },
    { name: 'Kittian and Nevisian' },
    { name: 'Korean' },
    { name: 'Kuwaiti' },
    { name: 'Kyrgyzstani' },
    { name: 'Laotian' },
    { name: 'Latvian' },
    { name: 'Lebanese' },
    { name: 'Lesotho' },
    { name: 'Liberian' },
    { name: 'Libyan' },
    { name: 'Liechtenstein' },
    { name: 'Lithuanian' },
    { name: 'Luxembourgish' },
    { name: 'Macedonian' },
    { name: 'Malagasy' },
    { name: 'Malawian' },
    { name: 'Malaysian' },
    { name: 'Maldivian' },
    { name: 'Malian' },
    { name: 'Malta' },
    { name: 'Marshallese' },
    { name: 'Mauritian' },
    { name: 'Mauritanian' },
    { name: 'Mexican' },
    { name: 'Micronesian' },
    { name: 'Moldovan' },
    { name: 'Monacan' },
    { name: 'Mongolian' },
    { name: 'Moroccan' },
    { name: 'Mozambican' },
    { name: 'Namibian' },
    { name: 'Nauruan' },
    { name: 'Nepalese' },
    { name: 'New Zealand' },
    { name: 'Nicaraguan' },
    { name: 'Nigerian' },
    { name: 'Nigerien' },
    { name: 'Norwegian' },
    { name: 'Omani' },
    { name: 'Pakistani' },
    { name: 'Palauan' },
    { name: 'Panamanian' },
    { name: 'Papua New Guinean' },
    { name: 'Paraguayan' },
    { name: 'Peruvian' },
    { name: 'Polish' },
    { name: 'Portuguese' },
    { name: 'Qatari' },
    { name: 'Romanian' },
    { name: 'Russian' },
    { name: 'Rwandan' },
    { name: 'Saint Kitts and Nevisian' },
    { name: 'Saint Lucian' },
    { name: 'Saint Vincentian' },
    { name: 'Salvadoran' },
    { name: 'Samoan' },
    { name: 'San Marino' },
    { name: 'Sao Tomean' },
    { name: 'Saudi' },
    { name: 'Senegalese' },
    { name: 'Serbian' },
    { name: 'Seychellois' },
    { name: 'Sierra Leonean' },
    { name: 'Singaporean' },
    { name: 'Slovak' },
    { name: 'Slovenian' },
    { name: 'Solomon Islands' },
    { name: 'Somali' },
    { name: 'South African' },
    { name: 'South Korean' },
    { name: 'Spanish' },
    { name: 'Sri Lankan' },
    { name: 'Sudanese' },
    { name: 'Surinamese' },
    { name: 'Swazi' },
    { name: 'Swedish' },
    { name: 'Swiss' },
    { name: 'Syrian' },
    { name: 'Taiwanese' },
    { name: 'Tajikistani' },
    { name: 'Tanzanian' },
    { name: 'Thai' },
    { name: 'Togolese' },
    { name: 'Tongan' },
    { name: 'Trinidadian and Tobagonian' },
    { name: 'Tunisian' },
    { name: 'Turkish' },
    { name: 'Turkmenistani' },
    { name: 'Tuvaluan' },
    { name: 'Ugandan' },
    { name: 'Ukrainian' },
    { name: 'Uruguayan' },
    { name: 'Uzbekistani' },
    { name: 'Venezuelan' },
    { name: 'Vietnamese' },
    { name: 'Yemeni' },
    { name: 'Zambian' },
    { name: 'Zimbabwean' },
  ];
  
  