# Generated by Django 5.0.11 on 2025-02-12 07:52

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('valid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('id_no', models.CharField(blank=True, max_length=100, null=True)),
                ('work_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city_residence', models.CharField(blank=True, max_length=255, null=True)),
                ('state_residence', models.CharField(blank=True, max_length=255, null=True)),
                ('same_address', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('agreeToPrivacy', models.BooleanField(default=False)),
                ('isOver21', models.BooleanField(default=False)),
                ('permanent_street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_until', models.CharField(blank=True, max_length=255, null=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='user_ids/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='user_ids/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('groups', models.ManyToManyField(blank=True, related_name='custommeber_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custommember_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
