# Generated by Django 5.1.5 on 2025-01-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permanent_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='present_address',
            field=models.BooleanField(default=False),
        ),
    ]
