# Generated by Django 5.1.5 on 2025-01-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0004_customuser_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
