# Generated by Django 5.0.11 on 2025-02-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0005_customuser_street_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='permanent_address',
            new_name='same_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='present_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanent_street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
