# Generated by Django 5.0.11 on 2025-02-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0006_rename_permanent_address_customuser_same_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
