# Generated by Django 5.0.11 on 2025-02-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0007_customuser_city_residence_customuser_state_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
