# Generated by Django 5.0.11 on 2025-02-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0008_customuser_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country_residence',
        ),
        migrations.AddField(
            model_name='customuser',
            name='countryCode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
