# Generated by Django 5.0.11 on 2025-02-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0009_remove_customuser_country_residence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='countryCode',
        ),
    ]
