# Generated by Django 5.0.11 on 2025-02-05 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0010_remove_customuser_countrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='latest_pics/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_pics', to='FormRecords.customuser')),
            ],
        ),
    ]
