# Generated by Django 5.0.11 on 2025-02-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0011_latestpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latest_pic',
            field=models.ImageField(blank=True, null=True, upload_to='latest_pics/'),
        ),
        migrations.DeleteModel(
            name='LatestPic',
        ),
    ]
