# Generated by Django 5.0.11 on 2025-02-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0012_customuser_latest_pic_delete_latestpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latest_pic',
        ),
    ]
