# Generated by Django 5.1.5 on 2025-02-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0016_alter_customuser_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='valid_until',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
