# Generated by Django 5.1.5 on 2025-02-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0017_customuser_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='user_ids/'),
        ),
    ]
