# Generated by Django 5.1.5 on 2025-02-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0018_customuser_id_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='user_ids/'),
        ),
    ]
