# Generated by Django 5.1.5 on 2025-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormRecords', '0020_customuser_date_of_birth_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='privacy_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
